name: language_helper_example
description: A comprehensive example demonstrating all features of the language_helper plugin.

publish_to: "none"

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^1.1.0
  language_helper:
    path: ../
  language_improver: ^0.0.1

dependency_overrides:
  language_helper:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/languages/codes.json
    - assets/languages/data/

