name: language_helper
description: A Flutter package for easy multi-language app localization with automatic text extraction and translation support.
version: 0.13.0-rc.8
homepage: https://github.com/lamnhan066/language_helper
topics:
  - localization
  - internationalization
  - language
  - i18n
  - l10n

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

platforms:
  android:
  ios:
  windows:
  linux:
  macos:
  web:

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  language_code: ^0.6.0-rc.4
  shared_preferences: ^2.0.0
  http: ^1.0.0
  lite_logger: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
